# Generated by Django 3.2.4 on 2021-10-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo_txt', models.CharField(choices=[('delimitado', 'delimitado'), ('ancho_fijo', 'ancho_fijo')], max_length=60)),
                ('delimitador', models.CharField(blank=True, max_length=10, null=True)),
                ('columnas', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('prueba', models.TextField()),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'reportes',
            },
        ),
    ]
